name: chem_revolutions
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  # google_fonts: ^6.3.3
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  intl: ^0.20.2
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.12.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/icons/google_logo.png
  - assets/icons/chemo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf # Corresponds to w900/w800 used in code
          weight: 900